//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abbSolutions.Communication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MaxSimultaneousIncomingConnections {
            get {
                return ((int)(this["MaxSimultaneousIncomingConnections"]));
            }
            set {
                this["MaxSimultaneousIncomingConnections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxSendThreads {
            get {
                return ((int)(this["MaxSendThreads"]));
            }
            set {
                this["MaxSendThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MaxReceiveThreads {
            get {
                return ((int)(this["MaxReceiveThreads"]));
            }
            set {
                this["MaxReceiveThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxProcessThreads {
            get {
                return ((int)(this["MaxProcessThreads"]));
            }
            set {
                this["MaxProcessThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int MaxAcceptIncomingThreads {
            get {
                return ((int)(this["MaxAcceptIncomingThreads"]));
            }
            set {
                this["MaxAcceptIncomingThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public int JoinPacketsIfSizeBelow {
            get {
                return ((int)(this["JoinPacketsIfSizeBelow"]));
            }
            set {
                this["JoinPacketsIfSizeBelow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600000")]
        public int MaxIncomingBytesToReadAtOnce {
            get {
                return ((int)(this["MaxIncomingBytesToReadAtOnce"]));
            }
            set {
                this["MaxIncomingBytesToReadAtOnce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("131072")]
        public int MaxOutgoingPacketSize {
            get {
                return ((int)(this["MaxOutgoingPacketSize"]));
            }
            set {
                this["MaxOutgoingPacketSize"] = value;
            }
        }
    }
}
